version: '3'
services:
  mlbootcamp:
    image: "kylehounslow/mlbootcamp:latest"
    ports:
     - "$API_PORT:$API_PORT"
     - "$JUPYTER_PORT:$JUPYTER_PORT"
    volumes:
     - "${PROJECT_DIR}:/home/ml"
    command: /usr/local/bin/jupyter-notebook  --no-browser --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token= --NotebookApp.password=
    environment:
     - API_PORT=$API_PORT

